---
title: 'PVAC Results Archive'
description: 'A site to publish swim meet results from various leagues.'
keywords: 'swim, meet, meet results, meet manager, sal'
authorName: 'Bryan Chain'
authorUrl: 'https://bryanchain.com'
githubUrl: 'https://github.com/werkkrew/swim-archive'
favicon: '/assets/images/meta/favicon.svg'
themeColor: '#FFAABB'
